# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dog Scanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dog Scanner
  # Pods for ImageClassification
   pod 'TensorFlowLiteSwift'

  target 'Dog ScannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Dog ScannerUITests' do
    # Pods for testing
  end

end
